version: '3'

services:
  # mysql development container
  mysqldb: 
    image: mysql:5.7
    restart: always
    # use ports when exposing port to external or local machine
    # docker containers can communicate with each other using network ips
    # ports:
    #   - "3007:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
      - MYSQL_DATABASE=${DBDATABASE}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASSWORD}
    volumes:
      # volume attaches to local file system
      - ./db:/var/lib/mysql
      # named volume eg
      # mysql-db:/var/lib/mysql where mysql-db is name of volume

  # node app container
  alliance-lowa-app:
    build: .
    ports:
      # node port mapping
      - "5000:4435"

    environment:
      # env default port
      - PORT=4435

# we have to declare all volumes which are be shared among different container instances
# volumes:
  # declare volume below
