name: Deploy Alliance Lowa Backend
on:
    pull_request:
        branches: [production]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout from production branch
            - name: Checkout to production
              uses: actions/checkout@v2

            # Copying files and artifacts via SSH
            - name: Copying files to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.DEPLOY_SECRET }}
                  rm: true
                  source: "./"
                  target: "${{ secrets.REMOTE_DIR }}"

            # Start backend container
            - name: Run Backend contianer
              uses: appleboy/ssh-action@master
              env:
                  DBHOST: ${{ secrets.DBHOST }}
                  DBPORT: ${{ secrets.DBPORT }}
                  DBUSER: ${{ secrets.DBUSER }}
                  DBPASSWORD: ${{ secrets.DBPASSWORD }}
                  DBDATABASE: ${{ secrets.DBDATABASE }}
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.DEPLOY_SECRET }}
                  script: sudo chmod u+x ./start_script.sh && ./start_script.sh
