name: Deploy Alliance Lowa Backend
on:
    pull_request:
        branches: [production]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Copying files and artifacts via SSH
            - name: scp pipeline
              uses: cross-the-world/scp-pipeline@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  user: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.DEPLOY_SECRET }}
                  local: "./**"
                  remote: "${{ secrets.REMOTE_DIR }}"

            # # Start backend container
            # - name: Run Backend contianer
            #   uses: appleboy/ssh-action@master
            #   env:
            #       DBHOST: ${{ secrets.DBHOST }}
            #       DBPORT: ${{ secrets.DBPORT }}
            #       DBUSER: ${{ secrets.DBUSER }}
            #       DBPASSWORD: ${{ secrets.DBPASSWORD }}
            #       DBDATABASE: ${{ secrets.DBDATABASE }}
            #   with:
            #       host: ${{ secrets.REMOTE_HOST }}
            #       username: ${{ secrets.REMOTE_USER }}
            #       key: ${{ secrets.DEPLOY_SECRET }}
            #       envs: DBHOST,DBPORT,DBUSER,DBPASSWORD,DBDATABASE
            #       script: sudo chmod u+x ./start_script.sh && ./start_script.sh
