name: Deploy Alliance Lowa Backend
on:
    pull_request:
        branches: [production]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout from production branch
            - name: Checkout to production
              uses: actions/checkout@v2

            # Copying files and artifacts via SSH
            - name: scp pipeline
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SECRET }}
                  SOURCE: ""
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_DIR }}
                  EXCLUDE: "/.git"

            # Start backend container
            - name: docker run pipeline
              uses: appleboy/ssh-action@master
              env:
                  PORT: "${{ secrets.PORT }}"
                  DBPORT: "${{ secrets.DBPORT }}"
                  DBHOST: "${{ secrets.DBHOST }}"
                  DBUSER: "${{ secrets.DBUSER }}"
                  DBDATABASE: "${{ secrets.DBDATABASE }}"
                  DBPASSWORD: "${{ secrets.DBPASSWORD }}"
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  timeout: "60"
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.DEPLOY_SECRET }}
                  envs: PORT, DBPORT, DBHOST, DBUSER, DBDATABASE, DBPASSWORD
                  script: |
                      echo "export PORT=$PORT" | cat >> .profile
                  #   cd ~/backend
                  #   sudo chmod u+x start_script.sh
                  #   ./start_script.sh
